application.name=order-acknowledge-mongodb
info.app.version=1.0.0
info.app.description=Order Fulfillment System (MongoDB) - Acknowledge (stateless ACL)

rest.automation=false
server.port=8093

log.format=json

web.component.scan=com.accenture

cloud.connector=none

kafka.bootstrap.servers=localhost:9092
kafka.flow.max.retries=3
kafka.flow.retry.backoff.ms=500

yaml.flow.automation=classpath:/flows.yaml
yaml.kafka.flow.adapter=classpath:/kafka-flow-adapter.yaml

snake.case.serialization=true
show.application.properties=server.port, cloud.connector
