application.name=order-manager-mongodb
info.app.version=1.0.0
info.app.description=Order Fulfillment System (MongoDB) - Manager

rest.server.port=8081
rest.automation=true
server.port=8091

log.format=json

web.component.scan=com.accenture

cloud.connector=none

spring.data.mongodb.uri=mongodb://order:order@localhost:27017/?authSource=admin
spring.data.mongodb.database=order_manager

kafka.bootstrap.servers=localhost:9092
kafka.flow.max.retries=3
kafka.flow.retry.backoff.ms=500

yaml.rest.automation=classpath:/rest.yaml
yaml.flow.automation=classpath:/flows.yaml
yaml.kafka.flow.adapter=classpath:/kafka-flow-adapter.yaml
yaml.cron=classpath:/cron.yaml

api.origin=*
snake.case.serialization=true

demo.mode=${DEMO_MODE:false}
show.application.properties=server.port, cloud.connector
