application.name=order-external-mock
info.app.version=1.0.0
info.app.description=Order Fulfillment System (MongoDB) - External Mock (SoR + order submission)

rest.server.port=8084
rest.automation=true
server.port=8094

log.format=json

web.component.scan=com.accenture

cloud.connector=none

kafka.bootstrap.servers=localhost:9092
kafka.flow.max.retries=3
kafka.flow.retry.backoff.ms=500

yaml.rest.automation=classpath:/rest.yaml
yaml.flow.automation=classpath:/flows.yaml
yaml.kafka.flow.adapter=classpath:/kafka-flow-adapter.yaml

api.origin=*
snake.case.serialization=true

demo.mode=${DEMO_MODE:false}
show.application.properties=server.port, cloud.connector
