spring.application.name=plan-fund-merge
info.app.version=1.0.0
info.app.description=Plan Fund Merge API

rest.server.port=8086
rest.automation=true
yaml.rest.automation=classpath:/rest.yaml
yaml.flow.automation=classpath:/flows.yaml

graph.model.automation=classpath:/graphs.yaml

log.format=text
cloud.connector=none
snake.case.serialization=true

web.component.scan=com.accenture

mandatory.health.dependencies=graph.health
