/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq.tables;


import home.jerry.test.jooq.Indexes;
import home.jerry.test.jooq.Keys;
import home.jerry.test.jooq.Token;
import home.jerry.test.jooq.tables.Service.ServicePath;
import home.jerry.test.jooq.tables.Tokendata.TokendataPath;
import home.jerry.test.jooq.tables.records.ServicetokendataRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Servicetokendata extends TableImpl<ServicetokendataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Token.ServiceTokenData</code>
     */
    public static final Servicetokendata SERVICETOKENDATA = new Servicetokendata();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServicetokendataRecord> getRecordType() {
        return ServicetokendataRecord.class;
    }

    /**
     * The column <code>Token.ServiceTokenData.Id</code>.
     */
    public final TableField<ServicetokendataRecord, Integer> ID = createField(DSL.name("Id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Token.ServiceTokenData.ServiceId</code>.
     */
    public final TableField<ServicetokendataRecord, Integer> SERVICEID = createField(DSL.name("ServiceId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Token.ServiceTokenData.TokenDataId</code>.
     */
    public final TableField<ServicetokendataRecord, Integer> TOKENDATAID = createField(DSL.name("TokenDataId"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Token.ServiceTokenData.CreatedAtUtc</code>.
     */
    public final TableField<ServicetokendataRecord, LocalDateTime> CREATEDATUTC = createField(DSL.name("CreatedAtUtc"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>Token.ServiceTokenData.UpdatedAtUtc</code>.
     */
    public final TableField<ServicetokendataRecord, LocalDateTime> UPDATEDATUTC = createField(DSL.name("UpdatedAtUtc"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>Token.ServiceTokenData.IsArchived</code>.
     */
    public final TableField<ServicetokendataRecord, Byte> ISARCHIVED = createField(DSL.name("IsArchived"), SQLDataType.TINYINT.nullable(false), this, "");

    private Servicetokendata(Name alias, Table<ServicetokendataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Servicetokendata(Name alias, Table<ServicetokendataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Token.ServiceTokenData</code> table reference
     */
    public Servicetokendata(String alias) {
        this(DSL.name(alias), SERVICETOKENDATA);
    }

    /**
     * Create an aliased <code>Token.ServiceTokenData</code> table reference
     */
    public Servicetokendata(Name alias) {
        this(alias, SERVICETOKENDATA);
    }

    /**
     * Create a <code>Token.ServiceTokenData</code> table reference
     */
    public Servicetokendata() {
        this(DSL.name("ServiceTokenData"), null);
    }

    public <O extends Record> Servicetokendata(Table<O> path, ForeignKey<O, ServicetokendataRecord> childPath, InverseForeignKey<O, ServicetokendataRecord> parentPath) {
        super(path, childPath, parentPath, SERVICETOKENDATA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServicetokendataPath extends Servicetokendata implements Path<ServicetokendataRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServicetokendataPath(Table<O> path, ForeignKey<O, ServicetokendataRecord> childPath, InverseForeignKey<O, ServicetokendataRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServicetokendataPath(Name alias, Table<ServicetokendataRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServicetokendataPath as(String alias) {
            return new ServicetokendataPath(DSL.name(alias), this);
        }

        @Override
        public ServicetokendataPath as(Name alias) {
            return new ServicetokendataPath(alias, this);
        }

        @Override
        public ServicetokendataPath as(Table<?> alias) {
            return new ServicetokendataPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Token.TOKEN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SERVICETOKENDATA_IX_SERVICETOKENDATA_SERVICEID, Indexes.SERVICETOKENDATA_IX_SERVICETOKENDATA_TOKENDATAID);
    }

    @Override
    public Identity<ServicetokendataRecord, Integer> getIdentity() {
        return (Identity<ServicetokendataRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServicetokendataRecord> getPrimaryKey() {
        return Keys.KEY_SERVICETOKENDATA_PRIMARY;
    }

    @Override
    public List<ForeignKey<ServicetokendataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SERVICETOKENDATA_SERVICE_SERVICEID, Keys.FK_SERVICETOKENDATA_TOKENDATA_TOKENDATAID);
    }

    private transient ServicePath _service;

    /**
     * Get the implicit join path to the <code>Token.Service</code> table.
     */
    public ServicePath service() {
        if (_service == null)
            _service = new ServicePath(this, Keys.FK_SERVICETOKENDATA_SERVICE_SERVICEID, null);

        return _service;
    }

    private transient TokendataPath _tokendata;

    /**
     * Get the implicit join path to the <code>Token.TokenData</code> table.
     */
    public TokendataPath tokendata() {
        if (_tokendata == null)
            _tokendata = new TokendataPath(this, Keys.FK_SERVICETOKENDATA_TOKENDATA_TOKENDATAID, null);

        return _tokendata;
    }

    @Override
    public Servicetokendata as(String alias) {
        return new Servicetokendata(DSL.name(alias), this);
    }

    @Override
    public Servicetokendata as(Name alias) {
        return new Servicetokendata(alias, this);
    }

    @Override
    public Servicetokendata as(Table<?> alias) {
        return new Servicetokendata(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetokendata rename(String name) {
        return new Servicetokendata(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetokendata rename(Name name) {
        return new Servicetokendata(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Servicetokendata rename(Table<?> name) {
        return new Servicetokendata(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata where(Condition condition) {
        return new Servicetokendata(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetokendata where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetokendata where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetokendata where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Servicetokendata where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Servicetokendata whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
