/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq.tables;


import home.jerry.test.jooq.Keys;
import home.jerry.test.jooq.Token;
import home.jerry.test.jooq.tables.Servicetokendata.ServicetokendataPath;
import home.jerry.test.jooq.tables.records.ServiceRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Service extends TableImpl<ServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Token.Service</code>
     */
    public static final Service SERVICE = new Service();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ServiceRecord> getRecordType() {
        return ServiceRecord.class;
    }

    /**
     * The column <code>Token.Service.Id</code>.
     */
    public final TableField<ServiceRecord, Integer> ID = createField(DSL.name("Id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Token.Service.Name</code>.
     */
    public final TableField<ServiceRecord, String> NAME = createField(DSL.name("Name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>Token.Service.CreatedAtUtc</code>.
     */
    public final TableField<ServiceRecord, LocalDateTime> CREATEDATUTC = createField(DSL.name("CreatedAtUtc"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>Token.Service.UpdatedAtUtc</code>.
     */
    public final TableField<ServiceRecord, LocalDateTime> UPDATEDATUTC = createField(DSL.name("UpdatedAtUtc"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>Token.Service.IsArchived</code>.
     */
    public final TableField<ServiceRecord, Byte> ISARCHIVED = createField(DSL.name("IsArchived"), SQLDataType.TINYINT.nullable(false), this, "");

    private Service(Name alias, Table<ServiceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Service(Name alias, Table<ServiceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>Token.Service</code> table reference
     */
    public Service(String alias) {
        this(DSL.name(alias), SERVICE);
    }

    /**
     * Create an aliased <code>Token.Service</code> table reference
     */
    public Service(Name alias) {
        this(alias, SERVICE);
    }

    /**
     * Create a <code>Token.Service</code> table reference
     */
    public Service() {
        this(DSL.name("Service"), null);
    }

    public <O extends Record> Service(Table<O> path, ForeignKey<O, ServiceRecord> childPath, InverseForeignKey<O, ServiceRecord> parentPath) {
        super(path, childPath, parentPath, SERVICE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ServicePath extends Service implements Path<ServiceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ServicePath(Table<O> path, ForeignKey<O, ServiceRecord> childPath, InverseForeignKey<O, ServiceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ServicePath(Name alias, Table<ServiceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ServicePath as(String alias) {
            return new ServicePath(DSL.name(alias), this);
        }

        @Override
        public ServicePath as(Name alias) {
            return new ServicePath(alias, this);
        }

        @Override
        public ServicePath as(Table<?> alias) {
            return new ServicePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Token.TOKEN;
    }

    @Override
    public Identity<ServiceRecord, Integer> getIdentity() {
        return (Identity<ServiceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ServiceRecord> getPrimaryKey() {
        return Keys.KEY_SERVICE_PRIMARY;
    }

    @Override
    public List<UniqueKey<ServiceRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SERVICE_IX_SERVICE_NAME);
    }

    private transient ServicetokendataPath _servicetokendata;

    /**
     * Get the implicit to-many join path to the
     * <code>Token.ServiceTokenData</code> table
     */
    public ServicetokendataPath servicetokendata() {
        if (_servicetokendata == null)
            _servicetokendata = new ServicetokendataPath(this, null, Keys.FK_SERVICETOKENDATA_SERVICE_SERVICEID.getInverseKey());

        return _servicetokendata;
    }

    @Override
    public Service as(String alias) {
        return new Service(DSL.name(alias), this);
    }

    @Override
    public Service as(Name alias) {
        return new Service(alias, this);
    }

    @Override
    public Service as(Table<?> alias) {
        return new Service(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(String name) {
        return new Service(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Name name) {
        return new Service(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Service rename(Table<?> name) {
        return new Service(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Condition condition) {
        return new Service(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Service where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Service whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
