/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq.tables.records;


import home.jerry.test.jooq.tables.Service;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServiceRecord extends UpdatableRecordImpl<ServiceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Token.Service.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Token.Service.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Token.Service.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Token.Service.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Token.Service.CreatedAtUtc</code>.
     */
    public void setCreatedatutc(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>Token.Service.CreatedAtUtc</code>.
     */
    public LocalDateTime getCreatedatutc() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>Token.Service.UpdatedAtUtc</code>.
     */
    public void setUpdatedatutc(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Token.Service.UpdatedAtUtc</code>.
     */
    public LocalDateTime getUpdatedatutc() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Token.Service.IsArchived</code>.
     */
    public void setIsarchived(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>Token.Service.IsArchived</code>.
     */
    public Byte getIsarchived() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServiceRecord
     */
    public ServiceRecord() {
        super(Service.SERVICE);
    }

    /**
     * Create a detached, initialised ServiceRecord
     */
    public ServiceRecord(Integer id, String name, LocalDateTime createdatutc, LocalDateTime updatedatutc, Byte isarchived) {
        super(Service.SERVICE);

        setId(id);
        setName(name);
        setCreatedatutc(createdatutc);
        setUpdatedatutc(updatedatutc);
        setIsarchived(isarchived);
        resetChangedOnNotNull();
    }
}
