/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq.tables.records;


import home.jerry.test.jooq.tables.Servicetokendata;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ServicetokendataRecord extends UpdatableRecordImpl<ServicetokendataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Token.ServiceTokenData.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Token.ServiceTokenData.ServiceId</code>.
     */
    public void setServiceid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.ServiceId</code>.
     */
    public Integer getServiceid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>Token.ServiceTokenData.TokenDataId</code>.
     */
    public void setTokendataid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.TokenDataId</code>.
     */
    public Integer getTokendataid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Token.ServiceTokenData.CreatedAtUtc</code>.
     */
    public void setCreatedatutc(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.CreatedAtUtc</code>.
     */
    public LocalDateTime getCreatedatutc() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Token.ServiceTokenData.UpdatedAtUtc</code>.
     */
    public void setUpdatedatutc(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.UpdatedAtUtc</code>.
     */
    public LocalDateTime getUpdatedatutc() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>Token.ServiceTokenData.IsArchived</code>.
     */
    public void setIsarchived(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>Token.ServiceTokenData.IsArchived</code>.
     */
    public Byte getIsarchived() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ServicetokendataRecord
     */
    public ServicetokendataRecord() {
        super(Servicetokendata.SERVICETOKENDATA);
    }

    /**
     * Create a detached, initialised ServicetokendataRecord
     */
    public ServicetokendataRecord(Integer id, Integer serviceid, Integer tokendataid, LocalDateTime createdatutc, LocalDateTime updatedatutc, Byte isarchived) {
        super(Servicetokendata.SERVICETOKENDATA);

        setId(id);
        setServiceid(serviceid);
        setTokendataid(tokendataid);
        setCreatedatutc(createdatutc);
        setUpdatedatutc(updatedatutc);
        setIsarchived(isarchived);
        resetChangedOnNotNull();
    }
}
