/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq.tables.records;


import home.jerry.test.jooq.tables.Tenant;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TenantRecord extends UpdatableRecordImpl<TenantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Token.Tenant.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Token.Tenant.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Token.Tenant.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Token.Tenant.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Token.Tenant.TenantType</code>.
     */
    public void setTenanttype(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>Token.Tenant.TenantType</code>.
     */
    public Integer getTenanttype() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>Token.Tenant.CreatedAtUtc</code>.
     */
    public void setCreatedatutc(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>Token.Tenant.CreatedAtUtc</code>.
     */
    public LocalDateTime getCreatedatutc() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>Token.Tenant.UpdatedAtUtc</code>.
     */
    public void setUpdatedatutc(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>Token.Tenant.UpdatedAtUtc</code>.
     */
    public LocalDateTime getUpdatedatutc() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>Token.Tenant.IsArchived</code>.
     */
    public void setIsarchived(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>Token.Tenant.IsArchived</code>.
     */
    public Byte getIsarchived() {
        return (Byte) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TenantRecord
     */
    public TenantRecord() {
        super(Tenant.TENANT);
    }

    /**
     * Create a detached, initialised TenantRecord
     */
    public TenantRecord(Integer id, String name, Integer tenanttype, LocalDateTime createdatutc, LocalDateTime updatedatutc, Byte isarchived) {
        super(Tenant.TENANT);

        setId(id);
        setName(name);
        setTenanttype(tenanttype);
        setCreatedatutc(createdatutc);
        setUpdatedatutc(updatedatutc);
        setIsarchived(isarchived);
        resetChangedOnNotNull();
    }
}
