/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq;


import home.jerry.test.jooq.tables.Servicetokendata;
import home.jerry.test.jooq.tables.Tokendata;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in Token.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SERVICETOKENDATA_IX_SERVICETOKENDATA_SERVICEID = Internal.createIndex(DSL.name("IX_ServiceTokenData_ServiceId"), Servicetokendata.SERVICETOKENDATA, new OrderField[] { Servicetokendata.SERVICETOKENDATA.SERVICEID }, false);
    public static final Index SERVICETOKENDATA_IX_SERVICETOKENDATA_TOKENDATAID = Internal.createIndex(DSL.name("IX_ServiceTokenData_TokenDataId"), Servicetokendata.SERVICETOKENDATA, new OrderField[] { Servicetokendata.SERVICETOKENDATA.TOKENDATAID }, false);
    public static final Index TOKENDATA_IX_TOKENDATA_TENANTID = Internal.createIndex(DSL.name("IX_TokenData_TenantId"), Tokendata.TOKENDATA, new OrderField[] { Tokendata.TOKENDATA.TENANTID }, false);
    public static final Index TOKENDATA_IX_TOKENDATA_TOKENTYPEID = Internal.createIndex(DSL.name("IX_TokenData_TokenTypeId"), Tokendata.TOKENDATA, new OrderField[] { Tokendata.TOKENDATA.TOKENTYPEID }, false);
}
