/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq;


import home.jerry.test.jooq.tables.Service;
import home.jerry.test.jooq.tables.Servicetokendata;
import home.jerry.test.jooq.tables.Tenant;
import home.jerry.test.jooq.tables.Tokendata;
import home.jerry.test.jooq.tables.Tokentype;


/**
 * Convenience access to all tables in Token.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>Token.Service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>Token.ServiceTokenData</code>.
     */
    public static final Servicetokendata SERVICETOKENDATA = Servicetokendata.SERVICETOKENDATA;

    /**
     * The table <code>Token.Tenant</code>.
     */
    public static final Tenant TENANT = Tenant.TENANT;

    /**
     * The table <code>Token.TokenData</code>.
     */
    public static final Tokendata TOKENDATA = Tokendata.TOKENDATA;

    /**
     * The table <code>Token.TokenType</code>.
     */
    public static final Tokentype TOKENTYPE = Tokentype.TOKENTYPE;
}
