/*
 * This file is generated by jOOQ.
 */
package home.jerry.test.jooq;


import home.jerry.test.jooq.tables.Service;
import home.jerry.test.jooq.tables.Servicetokendata;
import home.jerry.test.jooq.tables.Tenant;
import home.jerry.test.jooq.tables.Tokendata;
import home.jerry.test.jooq.tables.Tokentype;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Token extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Token</code>
     */
    public static final Token TOKEN = new Token();

    /**
     * The table <code>Token.Service</code>.
     */
    public final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>Token.ServiceTokenData</code>.
     */
    public final Servicetokendata SERVICETOKENDATA = Servicetokendata.SERVICETOKENDATA;

    /**
     * The table <code>Token.Tenant</code>.
     */
    public final Tenant TENANT = Tenant.TENANT;

    /**
     * The table <code>Token.TokenData</code>.
     */
    public final Tokendata TOKENDATA = Tokendata.TOKENDATA;

    /**
     * The table <code>Token.TokenType</code>.
     */
    public final Tokentype TOKENTYPE = Tokentype.TOKENTYPE;

    /**
     * No further instances allowed
     */
    private Token() {
        super("Token", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Service.SERVICE,
            Servicetokendata.SERVICETOKENDATA,
            Tenant.TENANT,
            Tokendata.TOKENDATA,
            Tokentype.TOKENTYPE
        );
    }
}
